trigger:
- main

pool:
  name: Default

variables:
  imageName: 'azure-devops-app'

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

- script: npm install
  displayName: Install dependencies

- script: npm test
  displayName: Run tests

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: 'ACR-Service-Connection'

- task: Docker@2
  displayName: Build Image
  inputs:
    command: build
    repository: $(imageName)
    dockerfile: Dockerfile
    tags: |
      $(Build.BuildId)

- task: Docker@2
  displayName: Push Image
  inputs:
    command: push
    repository: $(imageName)
    tags: |
      $(Build.BuildId)